version: '3.9'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - php
      - mysql
    volumes:
      -  .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        ACF_PRO_KEY: ${ACF_PRO_KEY}
    environment:
      DB_HOST: mysql:3306
      DB_USER: wordpress
      DB_PASSWORD: not-so-secure
      DB_NAME: wordpress
      WP_HOME: http://localhost:8000
      WP_SITEURL: http://localhost:8000/edition
      WP_ENV: development
      WP_INSTALLED: 1
      DEFAULT_URI: http://localhost:8000
      WP_MULTISITE: http://localhost:8000
      PUBLIC_PATH: http://localhost:8000/build/
      AUTH_KEY: "generateme"
      SECURE_AUTH_KEY: "generateme"
      LOGGED_IN_KEY: "generateme"
      NONCE_KEY: "generateme"
      AUTH_SALT: "generateme"
      SECURE_AUTH_SALT: "generateme"
      LOGGED_IN_SALT: "generateme"
      NONCE_SALT: "generateme"


  node:
    image: node:18
    depends_on:
      - nginx
    working_dir: /home/node/app
    command: bash -c "npm install && npm run dev-server"
    volumes:
      - .:/home/node/app
    ports:
      - 8080:8080
    restart: unless-stopped

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "9906:3306"
    environment:
      MYSQL_ROOT_PASSWORD: not-so-secure
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: not-so-secure
    volumes:
      - my-db:/var/lib/mysql
      - .:/home

volumes:
  my-db:
  root: